CREATE TABLE CLIENTE(
    ID_CLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUTO(
    ID_PRODUTO INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO numeric(20,2)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INTEGER REFERENCES CLIENTE(ID_CLIENTE),
    DATA_PEDIDO TIMESTAMP,
    STATUS_PEDIDO VARCHAR(20),
    TOTAL_PEDIDO NUMERIC(20,2)

);

CREATE TABLE ITEM_PEDIDO(
    ID_ITEM_PEDIDO INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INTEGER REFERENCES PEDIDO(ID_PEDIDO),
    ID_PRODUTO INTEGER REFERENCES PRODUTO(ID_PRODUTO),
    QUANTIDADE INTEGER
);

CREATE TABLE USUARIO(
    ID_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(200) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);